version: '3.8'

services:
  wms-app-prod:
    container_name: wms-app-prod
    build:
      context: .
      target: release
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_DEVICE_HUB=${NEXT_PUBLIC_DEVICE_HUB}
      - NEXT_PUBLIC_API_HUB=${NEXT_PUBLIC_API_HUB}
      - NEXT_PUBLIC_PUSHER_APP_ID=${NEXT_PUBLIC_PUSHER_APP_ID}
      - NEXT_PUBLIC_PUSHER_KEY=${NEXT_PUBLIC_PUSHER_KEY}
      - NEXT_PUBLIC_PUSHER_CLUSTER=${NEXT_PUBLIC_PUSHER_CLUSTER}
      - NEXT_PUBLIC_BASE_URL=http://103.174.115.64:3000
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
